In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [2]:
import pandas as pd
data=pd.read_csv("B2_heart.csv")
data.head()
x=data.drop("target",axis=1)
y=data.target

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [4]:
linear=svm.SVC(kernel="linear")
linear.fit(x_train,y_train)

print(linear.support_vectors_)

[[35.  1.  0. ...  2.  0.  3.]
 [59.  1.  3. ...  2.  0.  2.]
 [65.  1.  0. ...  2.  2.  1.]
 ...
 [56.  1.  1. ...  2.  0.  3.]
 [52.  1.  2. ...  2.  4.  2.]
 [43.  1.  2. ...  2.  1.  2.]]


In [5]:
print(linear.n_support_)
y_pred=linear.predict(x_test)

[41 41]


In [6]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8131868131868132


In [7]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[31 11]
 [ 6 43]]


In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.74      0.78        42
           1       0.80      0.88      0.83        49

    accuracy                           0.81        91
   macro avg       0.82      0.81      0.81        91
weighted avg       0.82      0.81      0.81        91



In [9]:
model1=SVC(kernel="sigmoid")
model2=SVC(kernel="poly")
model3=SVC(kernel="rbf")

In [10]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [11]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [12]:
print("prediction by model1",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred3))

prediction by model1 0.5384615384615384
prediction by model2 0.7142857142857143
prediction by model3 0.7032967032967034
